server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
logging:
    level:
        root: WARN
spring:
   application:
    name: loan-service
   datasource:
        password: s$cret
        url: jdbc:mysql://localhost:3306/testdb
        username: user12
   jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect



